ALTER TABLE `pl_applications` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'PLATFORM_REJECTED', 'ALLOCATION_PENDING', 'LENDER_ALLOCATED', 'LENDER_REVIEW', 'LENDER_PRE_APPROVED', 'PENDING_CREDIT_REVIEW', 'LENDER_APPROVED', 'LENDER_REJECTED', 'ASSESSMENT_FEE_PAID') NOT NULL DEFAULT 'DRAFT';

ALTER TABLE `customers` MODIFY `onboarding_status` ENUM('MOBILE_VERIFIED', 'BASIC_DETAILS_PENDING', 'PAN_VERIFIED', 'EMAIL_VERIFIED', 'PLATFORM_BRE_PENDING', 'PLATFORM_ELIGIBLE', 'PLATFORM_INELIGIBLE', 'APPLICATION_IN_PROGRESS', 'APPLICATION_SUBMITTED', 'LENDER_PRE_APPROVED', 'PENDING_CREDIT_REVIEW', 'LENDER_APPROVED', 'LENDER_REJECTED', 'DISBURSED') NOT NULL DEFAULT 'MOBILE_VERIFIED';

ALTER TABLE `pl_applications`
  ADD COLUMN `selected_amount` DECIMAL(15, 2) NULL AFTER `requested_tenure`,
  ADD COLUMN `selected_tenure` INT NULL AFTER `selected_amount`,
  ADD COLUMN `selected_at` DATETIME NULL AFTER `selected_tenure`;
