-- Add lender decision fields separately from customer requested amount.
ALTER TABLE `pl_applications`
  ADD COLUMN `lender_approved_amount` DECIMAL(15, 2) NULL,
  ADD COLUMN `lender_approved_tenure` INTEGER NULL,
  ADD COLUMN `lender_approved_roi` DECIMAL(7, 4) NULL,
  ADD COLUMN `lender_decision_reference` VARCHAR(150) NULL,
  ADD COLUMN `lender_cooling_off_days` INTEGER NULL,
  ADD COLUMN `lender_cooling_off_until` DATETIME(0) NULL,
  ADD COLUMN `lender_next_status_check_at` DATETIME(0) NULL;

CREATE TABLE `LenderIntegrationConfig` (
  `id` VARCHAR(191) NOT NULL,
  `lenderId` VARCHAR(191) NOT NULL,
  `adapterKey` VARCHAR(80) NOT NULL,
  `adapterVersion` VARCHAR(30) NOT NULL,
  `baseUrl` VARCHAR(500) NULL,
  `authType` ENUM('NONE', 'API_KEY', 'BEARER_TOKEN', 'BASIC', 'CUSTOM') NOT NULL DEFAULT 'NONE',
  `credentialSecretReference` VARCHAR(150) NULL,
  `createApplicationPath` VARCHAR(255) NULL,
  `updateApplicationPath` VARCHAR(255) NULL,
  `decisionPath` VARCHAR(255) NULL,
  `statusPath` VARCHAR(255) NULL,
  `webhookPath` VARCHAR(255) NULL,
  `webhookSecretReference` VARCHAR(150) NULL,
  `connectTimeoutMs` INTEGER NOT NULL DEFAULT 5000,
  `requestTimeoutMs` INTEGER NOT NULL DEFAULT 15000,
  `maximumRetryAttempts` INTEGER NOT NULL DEFAULT 5,
  `retryScheduleSeconds` VARCHAR(100) NOT NULL DEFAULT '0,60,300,900,3600',
  `isActive` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `uk_lender_integration_config_version`(`lenderId`, `adapterKey`, `adapterVersion`),
  INDEX `idx_lender_integration_config_active`(`lenderId`, `isActive`),
  INDEX `idx_lender_adapter_active`(`adapterKey`, `adapterVersion`, `isActive`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lender_integration_config_lender` FOREIGN KEY (`lenderId`) REFERENCES `Lender`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LenderDataSharingConsent` (
  `id` VARCHAR(191) NOT NULL,
  `applicationId` BIGINT UNSIGNED NOT NULL,
  `customerId` BIGINT UNSIGNED NOT NULL,
  `lenderId` VARCHAR(191) NOT NULL,
  `consentVersion` VARCHAR(50) NOT NULL,
  `consentTextHash` CHAR(64) NOT NULL,
  `consentReference` VARCHAR(150) NULL,
  `acceptedAt` DATETIME(3) NOT NULL,
  `ipAddress` VARCHAR(64) NULL,
  `userAgent` VARCHAR(512) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `uk_lender_consent_application_version`(`applicationId`, `lenderId`, `consentVersion`),
  INDEX `idx_lender_consent_customer`(`customerId`, `acceptedAt`),
  INDEX `idx_lender_consent_lender`(`lenderId`, `acceptedAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lender_consent_application` FOREIGN KEY (`applicationId`) REFERENCES `pl_applications`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_consent_customer` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_consent_lender` FOREIGN KEY (`lenderId`) REFERENCES `Lender`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LenderApplicationLink` (
  `id` VARCHAR(191) NOT NULL,
  `applicationId` BIGINT UNSIGNED NOT NULL,
  `applicationReference` VARCHAR(50) NOT NULL,
  `lenderId` VARCHAR(191) NOT NULL,
  `lenderProductId` VARCHAR(191) NOT NULL,
  `productStrategyVersionId` VARCHAR(191) NOT NULL,
  `integrationConfigId` VARCHAR(191) NOT NULL,
  `adapterKey` VARCHAR(80) NOT NULL,
  `adapterVersion` VARCHAR(30) NOT NULL,
  `partnerLeadId` VARCHAR(150) NULL,
  `partnerApplicationId` VARCHAR(150) NULL,
  `partnerReference` VARCHAR(150) NULL,
  `createStatus` ENUM('NOT_STARTED', 'PENDING', 'PROCESSING', 'ACKNOWLEDGED', 'RETRY_PENDING', 'FAILED', 'COMPLETED') NOT NULL DEFAULT 'NOT_STARTED',
  `updateStatus` ENUM('NOT_STARTED', 'PENDING', 'PROCESSING', 'ACKNOWLEDGED', 'RETRY_PENDING', 'FAILED', 'COMPLETED') NOT NULL DEFAULT 'NOT_STARTED',
  `decisionStatus` ENUM('NOT_STARTED', 'PENDING', 'PROCESSING', 'ACKNOWLEDGED', 'RETRY_PENDING', 'FAILED', 'COMPLETED') NOT NULL DEFAULT 'NOT_STARTED',
  `lastSyncedStage` ENUM('CREATE', 'UPDATE', 'DECISION', 'STATUS') NULL,
  `createIdempotencyKey` VARCHAR(191) NOT NULL,
  `updateIdempotencyKey` VARCHAR(191) NULL,
  `decisionIdempotencyKey` VARCHAR(191) NULL,
  `createPayloadVersion` INTEGER NOT NULL DEFAULT 1,
  `updatePayloadVersion` INTEGER NOT NULL DEFAULT 1,
  `decisionPayloadVersion` INTEGER NOT NULL DEFAULT 1,
  `normalizedDecision` ENUM('APPROVED', 'REJECTED', 'PENDING') NULL,
  `lastRequestHash` CHAR(64) NULL,
  `lastResponseStatus` VARCHAR(80) NULL,
  `lastAttemptAt` DATETIME(3) NULL,
  `lastSuccessAt` DATETIME(3) NULL,
  `lastErrorCode` VARCHAR(100) NULL,
  `lastErrorMessage` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `LenderApplicationLink_applicationId_key`(`applicationId`),
  UNIQUE INDEX `LenderApplicationLink_createIdempotencyKey_key`(`createIdempotencyKey`),
  UNIQUE INDEX `LenderApplicationLink_updateIdempotencyKey_key`(`updateIdempotencyKey`),
  UNIQUE INDEX `LenderApplicationLink_decisionIdempotencyKey_key`(`decisionIdempotencyKey`),
  INDEX `idx_lender_link_create_status`(`lenderId`, `createStatus`),
  INDEX `idx_lender_link_adapter`(`adapterKey`, `adapterVersion`),
  INDEX `idx_lender_link_partner_application`(`partnerApplicationId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lender_link_application` FOREIGN KEY (`applicationId`) REFERENCES `pl_applications`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_link_lender` FOREIGN KEY (`lenderId`) REFERENCES `Lender`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_link_product` FOREIGN KEY (`lenderProductId`) REFERENCES `LenderProduct`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_link_product_version` FOREIGN KEY (`productStrategyVersionId`) REFERENCES `LenderProductVersion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_link_config` FOREIGN KEY (`integrationConfigId`) REFERENCES `LenderIntegrationConfig`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LenderIntegrationOutbox` (
  `id` VARCHAR(191) NOT NULL,
  `eventType` ENUM('LENDER_CREATE_APPLICATION', 'LENDER_UPDATE_APPLICATION', 'LENDER_REQUEST_DECISION', 'LENDER_STATUS_CHECK') NOT NULL,
  `applicationId` BIGINT UNSIGNED NOT NULL,
  `applicationReference` VARCHAR(50) NOT NULL,
  `lenderId` VARCHAR(191) NOT NULL,
  `integrationStage` ENUM('CREATE', 'UPDATE', 'DECISION', 'STATUS') NOT NULL,
  `payloadVersion` INTEGER NOT NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `status` ENUM('PENDING', 'PROCESSING', 'RETRY_PENDING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING',
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `availableAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lockedAt` DATETIME(3) NULL,
  `lockedBy` VARCHAR(100) NULL,
  `processedAt` DATETIME(3) NULL,
  `lastErrorCode` VARCHAR(100) NULL,
  `lastErrorMessage` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `LenderIntegrationOutbox_idempotencyKey_key`(`idempotencyKey`),
  INDEX `idx_lender_outbox_ready`(`status`, `availableAt`, `createdAt`),
  INDEX `idx_lender_outbox_application_stage`(`applicationId`, `integrationStage`),
  INDEX `idx_lender_outbox_lender_status`(`lenderId`, `status`),
  INDEX `idx_lender_outbox_locked`(`lockedAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lender_outbox_application` FOREIGN KEY (`applicationId`) REFERENCES `pl_applications`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lender_outbox_lender` FOREIGN KEY (`lenderId`) REFERENCES `Lender`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
