ALTER TABLE `LenderIntegrationOutbox`
    MODIFY `eventType` ENUM('LENDER_CREATE_APPLICATION','LENDER_UPDATE_APPLICATION','LENDER_REQUEST_DECISION','LENDER_STATUS_CHECK','LENDER_SUBMIT_CONSENT','LENDER_UPLOAD_DOCUMENT','LENDER_REQUEST_DISBURSAL') NOT NULL;

ALTER TABLE `LenderIntegrationOutbox`
    MODIFY `integrationStage` ENUM('CREATE', 'UPDATE', 'DECISION', 'STATUS', 'CONSENT', 'DOCUMENT', 'DISBURSE') NOT NULL;

ALTER TABLE `LenderIntegrationConfig` ADD COLUMN `disbursePath` VARCHAR(255) NULL;
