-- AlterTable
ALTER TABLE `pl_applications` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'PLATFORM_REJECTED', 'ALLOCATION_PENDING', 'LENDER_ALLOCATED', 'LENDER_REVIEW', 'LENDER_PRE_APPROVED', 'PENDING_CREDIT_REVIEW', 'LENDER_APPROVED', 'LENDER_REJECTED', 'ASSESSMENT_FEE_PAID', 'LOAN_CLOSED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `pl_loans` MODIFY `status` ENUM('LENDER_APPROVED', 'OFFER_ACCEPTED', 'KYC_IN_PROGRESS', 'ADDRESS_CONFIRMED', 'BANK_VERIFIED', 'KFS_ACCEPTED', 'MANDATE_COMPLETED', 'ESIGN_COMPLETED', 'READY_FOR_DISBURSAL', 'DISBURSAL_PROCESSING', 'DISBURSED', 'FULLY_PAID', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'LENDER_APPROVED';
