-- AlterTable
ALTER TABLE `pl_loans` MODIFY `status` ENUM('LENDER_APPROVED', 'OFFER_ACCEPTED', 'KYC_IN_PROGRESS', 'ADDRESS_CONFIRMED', 'BANK_VERIFIED', 'KFS_ACCEPTED', 'MANDATE_COMPLETED', 'ESIGN_COMPLETED', 'READY_FOR_DISBURSAL', 'DISBURSAL_PROCESSING', 'DISBURSED', 'FULLY_PAID', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'LENDER_APPROVED';
